<p style="text-align:center">
    <a href="https://skills.network/?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkML0101ENSkillsNetwork20718538-2022-01-01">
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/assets/logos/SN_web_lightmode.png" width="200" alt="Skills Network Logo"  />
    </a>
</p>

<h1 align="center"><font size="5">Final Project: Classification with Python</font></h1>


<h2>Table of Contents</h2>
<div class="alert alert-block alert-info" style="margin-top: 20px">
    <ul>
    <li><a href="https://#Section_1">Instructions</a></li>
    <li><a href="https://#Section_2">About the Data</a></li>
    <li><a href="https://#Section_3">Importing Data </a></li>
    <li><a href="https://#Section_4">Data Preprocessing</a> </li>
    <li><a href="https://#Section_5">Transforming Categorical Variables </a></li>
    <li><a href="https://#Section_6">Train and Test Data Split </a></li>
    <li><a href="https://#Section_7">Train Linear Regression, KNN, Decision Tree, Logistic Regression, and SVM models and return their appropriate accuracy scores</a></li>
</a></li>
</div>
<p>Estimated Time Needed: <strong>180 min</strong></p>
</div>

<hr>


# Instructions


In this notebook, you will  practice all the classification algorithms that we learned in this course.

After completing this notebook, you will need to upload it to the "Submit Your Work and Review Your Peers" section of the Final Project module.

Below, is where we are going to use the classification algorithms to create a model based on our training data and evaluate our testing data using evaluation metrics learned in the course.

We will use some of the algorithms taught in the course, specifically:

1.  Linear Regression
2.  KNN
3.  Decision Trees
4.  Logistic Regression
5.  SVM

We will evaluate our models using:

1.  Accuracy Score
2.  Jaccard Index
3.  F1-Score
4.  LogLoss
5.  Mean Absolute Error
6.  Mean Squared Error
7.  R2-Score

Finally, you will use your models to generate the report displaying the accuracy scores.


# About The Dataset


The original source of the data is Australian Government's Bureau of Meteorology and the latest data can be gathered from [http://www.bom.gov.au/climate/dwo/](http://www.bom.gov.au/climate/dwo/?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkML0101ENSkillsNetwork20718538-2022-01-01).

The dataset to be used has extra columns like 'RainToday' and our target is 'RainTomorrow', which was gathered from the Rattle at [https://bitbucket.org/kayontoga/rattle/src/master/data/weatherAUS.RData](https://bitbucket.org/kayontoga/rattle/src/master/data/weatherAUS.RData?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkML0101ENSkillsNetwork20718538-2022-01-01)



This dataset contains observations of weather metrics for each day from 2008 to 2017. The **weatherAUS.csv** dataset includes the following fields:

| Field         | Description                                           | Unit            | Type   |
| ------------- | ----------------------------------------------------- | --------------- | ------ |
| Date          | Date of the Observation in YYYY-MM-DD                 | Date            | object |
| Location      | Location of the Observation                           | Location        | object |
| MinTemp       | Minimum temperature                                   | Celsius         | float  |
| MaxTemp       | Maximum temperature                                   | Celsius         | float  |
| Rainfall      | Amount of rainfall                                    | Millimeters     | float  |
| Evaporation   | Amount of evaporation                                 | Millimeters     | float  |
| Sunshine      | Amount of bright sunshine                             | hours           | float  |
| WindGustDir   | Direction of the strongest gust                       | Compass Points  | object |
| WindGustSpeed | Speed of the strongest gust                           | Kilometers/Hour | object |
| WindDir9am    | Wind direction averaged of 10 minutes prior to 9am    | Compass Points  | object |
| WindDir3pm    | Wind direction averaged of 10 minutes prior to 3pm    | Compass Points  | object |
| WindSpeed9am  | Wind speed averaged of 10 minutes prior to 9am        | Kilometers/Hour | float  |
| WindSpeed3pm  | Wind speed averaged of 10 minutes prior to 3pm        | Kilometers/Hour | float  |
| Humidity9am   | Humidity at 9am                                       | Percent         | float  |
| Humidity3pm   | Humidity at 3pm                                       | Percent         | float  |
| Pressure9am   | Atmospheric pressure reduced to mean sea level at 9am | Hectopascal     | float  |
| Pressure3pm   | Atmospheric pressure reduced to mean sea level at 3pm | Hectopascal     | float  |
| Cloud9am      | Fraction of the sky obscured by cloud at 9am          | Eights          | float  |
| Cloud3pm      | Fraction of the sky obscured by cloud at 3pm          | Eights          | float  |
| Temp9am       | Temperature at 9am                                    | Celsius         | float  |
| Temp3pm       | Temperature at 3pm                                    | Celsius         | float  |
| RainToday     | If there was rain today                               | Yes/No          | object |
| RISK_MM       | Amount of rain tomorrow                               | Millimeters     | float  |
| RainTomorrow  | If there is rain tomorrow                             | Yes/No          | float  |

Column definitions were gathered from [http://www.bom.gov.au/climate/dwo/IDCJDW0000.shtml](http://www.bom.gov.au/climate/dwo/IDCJDW0000.shtml?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkML0101ENSkillsNetwork20718538-2022-01-01)



## **Import the required libraries**


In [1]:
# All Libraries required for this lab are listed below. The libraries pre-installed on Skills Network Labs are commented.
# !mamba install -qy pandas==1.3.4 numpy==1.21.4 seaborn==0.9.0 matplotlib==3.5.0 scikit-learn==0.20.1
# Note: If your environment doesn't support "!mamba install", use "!pip install"

In [35]:
# Surpress warnings:
def warn(*args, **kwargs):
    pass
import warnings
warnings.warn = warn

In [36]:
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import LinearRegression
from sklearn import preprocessing
import numpy as np
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn import svm
from sklearn.metrics import jaccard_score
from sklearn.metrics import f1_score
from sklearn.metrics import log_loss
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix, accuracy_score
import sklearn.metrics as metrics

### Importing the Dataset


In [37]:
df = pd.read_csv('https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-ML0101EN-SkillUp/labs/ML-FinalAssignment/Weather_Data.csv')

df.head()

Date  MinTemp  MaxTemp  Rainfall  Evaporation  Sunshine WindGustDir  \
0  2/1/2008     19.5     22.4      15.6          6.2       0.0           W   
1  2/2/2008     19.5     25.6       6.0          3.4       2.7           W   
2  2/3/2008     21.6     24.5       6.6          2.4       0.1           W   
3  2/4/2008     20.2     22.8      18.8          2.2       0.0           W   
4  2/5/2008     19.7     25.7      77.4          4.8       0.0           W   

   WindGustSpeed WindDir9am WindDir3pm  WindSpeed9am  WindSpeed3pm  \
0             41          S        SSW            17            20   
1             41          W          E             9            13   
2             41        ESE        ESE            17             2   
3             41        NNE          E            22            20   
4             41        NNE          W            11             6   

   Humidity9am  Humidity3pm  Pressure9am  Pressure3pm  Cloud9am  Cloud3pm  \
0           92           84       1017.6       1017.4         8         8   
1           83           73       1017.9       1016.4         7         7   
2           88           86       1016.7       1015.6         7         8   
3           83           90       1014.2       1011.8         8         8   
4           88           74       1008.3       1004.8         8         8   

   Temp9am  Temp3pm RainToday RainTomorrow  
0     20.7     20.9       Yes          Yes  
1     22.4     24.8       Yes          Yes  
2     23.5     23.0       Yes          Yes  
3     21.4     20.9       Yes          Yes  
4     22.5     25.5       Yes          Yes

### Data Preprocessing


#### Transforming Categorical Variables


First, we need to convert categorical variables to binary variables. We will use pandas `get_dummies()` method for this.


In [38]:
df_sydney_processed = pd.get_dummies(data=df, columns=['RainToday', 'WindGustDir', 'WindDir9am', 'WindDir3pm'])

Next, we replace the values of the 'RainTomorrow' column changing them from a categorical column to a binary column. We do not use the `get_dummies` method because we would end up with two columns for 'RainTomorrow' and we do not want, since 'RainTomorrow' is our target.


In [39]:
df_sydney_processed.replace(['No', 'Yes'], [0,1], inplace=True)

### Training Data and Test Data


Now, we set our 'features' or x values and our Y or target variable.


In [40]:
df_sydney_processed.drop('Date',axis=1,inplace=True)

In [41]:
df_sydney_processed = df_sydney_processed.astype(float)
pd.set_option('display.max_columns',None)
df_sydney_processed.head()

MinTemp  MaxTemp  Rainfall  Evaporation  Sunshine  WindGustSpeed  \
0     19.5     22.4      15.6          6.2       0.0           41.0   
1     19.5     25.6       6.0          3.4       2.7           41.0   
2     21.6     24.5       6.6          2.4       0.1           41.0   
3     20.2     22.8      18.8          2.2       0.0           41.0   
4     19.7     25.7      77.4          4.8       0.0           41.0   

   WindSpeed9am  WindSpeed3pm  Humidity9am  Humidity3pm  Pressure9am  \
0          17.0          20.0         92.0         84.0       1017.6   
1           9.0          13.0         83.0         73.0       1017.9   
2          17.0           2.0         88.0         86.0       1016.7   
3          22.0          20.0         83.0         90.0       1014.2   
4          11.0           6.0         88.0         74.0       1008.3   

   Pressure3pm  Cloud9am  Cloud3pm  Temp9am  Temp3pm  RainTomorrow  \
0       1017.4       8.0       8.0     20.7     20.9           1.0   
1       1016.4       7.0       7.0     22.4     24.8           1.0   
2       1015.6       7.0       8.0     23.5     23.0           1.0   
3       1011.8       8.0       8.0     21.4     20.9           1.0   
4       1004.8       8.0       8.0     22.5     25.5           1.0   

   RainToday_No  RainToday_Yes  WindGustDir_E  WindGustDir_ENE  \
0           0.0            1.0            0.0              0.0   
1           0.0            1.0            0.0              0.0   
2           0.0            1.0            0.0              0.0   
3           0.0            1.0            0.0              0.0   
4           0.0            1.0            0.0              0.0   

   WindGustDir_ESE  WindGustDir_N  WindGustDir_NE  WindGustDir_NNE  \
0              0.0            0.0             0.0              0.0   
1              0.0            0.0             0.0              0.0   
2              0.0            0.0             0.0              0.0   
3              0.0            0.0             0.0              0.0   
4              0.0            0.0             0.0              0.0   

   WindGustDir_NNW  WindGustDir_NW  WindGustDir_S  WindGustDir_SE  \
0              0.0             0.0            0.0             0.0   
1              0.0             0.0            0.0             0.0   
2              0.0             0.0            0.0             0.0   
3              0.0             0.0            0.0             0.0   
4              0.0             0.0            0.0             0.0   

   WindGustDir_SSE  WindGustDir_SSW  WindGustDir_SW  WindGustDir_W  \
0              0.0              0.0             0.0            1.0   
1              0.0              0.0             0.0            1.0   
2              0.0              0.0             0.0            1.0   
3              0.0              0.0             0.0            1.0   
4              0.0              0.0             0.0            1.0   

   WindGustDir_WNW  WindGustDir_WSW  WindDir9am_E  WindDir9am_ENE  \
0              0.0              0.0           0.0             0.0   
1              0.0              0.0           0.0             0.0   
2              0.0              0.0           0.0             0.0   
3              0.0              0.0           0.0             0.0   
4              0.0              0.0           0.0             0.0   

   WindDir9am_ESE  WindDir9am_N  WindDir9am_NE  WindDir9am_NNE  \
0             0.0           0.0            0.0             0.0   
1             0.0           0.0            0.0             0.0   
2             1.0           0.0            0.0             0.0   
3             0.0           0.0            0.0             1.0   
4             0.0           0.0            0.0             1.0   

   WindDir9am_NNW  WindDir9am_NW  WindDir9am_S  WindDir9am_SE  WindDir9am_SSE  \
0             0.0            0.0           1.0            0.0             0.0   
1             0.0            0.0           0.0            0.0             0.0   
2            

In [42]:
features = df_sydney_processed.drop(columns='RainTomorrow', axis=1)
Y = df_sydney_processed['RainTomorrow']

### Linear Regression


#### Q1) Use the `train_test_split` function to split the `features` and `Y` dataframes with a `test_size` of `0.2` and the `random_state` set to `10`.


In [43]:
#Enter Your Code, Execute and take the Screenshot

In [53]:
x_train, x_test, y_train, y_test = train_test_split(features,Y,test_size=0.2,random_state=10)
print("Train size:",x_train.shape,y_train.shape)
print("Test size:",x_test.shape,y_test.shape)

Train size: (2616, 66) (2616,)
Test size: (655, 66) (655,)


#### Q2) Create and train a Linear Regression model called LinearReg using the training data (`x_train`, `y_train`).


In [45]:
#Enter Your Code, Execute and take the Screenshot

In [49]:
from sklearn import linear_model
LinearReg = linear_model.LinearRegression()
LinearReg.fit(features,Y)

LinearRegression()

#### Q3) Now use the `predict` method on the testing data (`x_test`) and save it to the array `predictions`.


In [ ]:
#Enter Your Code, Execute and take the Screenshot

In [51]:
predictions = LinearReg.predict(x_test)
predictions

array([ 1.02569580e-01,  2.86239624e-01,  9.73526001e-01,  2.88467407e-01,
        1.07299805e-01,  4.84375000e-01,  3.44863892e-01,  8.76678467e-01,
        6.83990479e-01,  3.36608887e-02, -3.60260010e-02,  3.12347412e-01,
        3.28353882e-01,  1.26480103e-01,  4.97894287e-02,  5.44998169e-01,
       -5.83953857e-02,  4.86267090e-01,  7.77587891e-02,  3.96163940e-01,
        4.45709229e-02,  9.28131104e-01,  4.87594604e-01,  2.17803955e-01,
       -6.36291504e-02,  3.92425537e-01,  5.22109985e-01, -9.21630859e-03,
        6.12335205e-01, -1.20254517e-01,  3.96835327e-01,  1.23809814e-01,
       -1.07421875e-02,  9.57031250e-02,  5.43914795e-01,  1.07289124e+00,
        5.34057617e-03,  5.15243530e-01, -6.08825684e-02,  5.20629883e-02,
        2.46582031e-02,  9.04830933e-01,  2.53402710e-01,  4.18991089e-01,
        3.04428101e-01,  4.58724976e-01, -2.22015381e-02,  1.81991577e-01,
        8.03558350e-01,  1.89422607e-01,  2.27813721e-02, -3.57360840e-02,
        2.21618652e-01, -

#### Q4) Using the `predictions` and the `y_test` dataframe calculate the value for each metric using the appropriate function.


In [ ]:
#Enter Your Code, Execute and take the Screenshot

In [55]:
from sklearn.metrics import r2_score
LinearRegression_MAE = np.mean(np.absolute(predictions-y_test))
LinearRegression_MSE = np.mean((predictions-y_test)**2)
LinearRegression_R2 = r2_score(y_test,predictions)

#### Q5) Show the MAE, MSE, and R2 in a tabular format using data frame for the linear model.


In [ ]:
#Enter Your Code, Execute and take the Screenshot

In [56]:
Report = {"Metrics":["MAE","MSE","R2"],"Result": [LinearRegression_MAE,LinearRegression_MSE,LinearRegression_R2]}
pd.DataFrame(Report)

Metrics    Result
0     MAE  0.250490
1     MSE  0.110519
2      R2  0.452884

### KNN


#### Q6) Create and train a KNN model called KNN using the training data (`x_train`, `y_train`) with the `n_neighbors` parameter set to `4`.


In [ ]:
#Enter Your Code, Execute and take the Screenshot

In [58]:
KNN = KNeighborsClassifier(n_neighbors=4).fit(x_train,y_train)
KNN

KNeighborsClassifier(n_neighbors=4)

#### Q7) Now use the `predict` method on the testing data (`x_test`) and save it to the array `predictions`.


In [ ]:
#Enter Your Code, Execute and take the Screenshot

In [59]:
predictions = KNN.predict(x_test)
predictions[0:5]

array([0., 0., 1., 0., 0.])

#### Q8) Using the `predictions` and the `y_test` dataframe calculate the value for each metric using the appropriate function.


In [ ]:
#Enter Your Code, Execute and take the Screenshot

In [152]:
KNN_Accuracy_Score = metrics.accuracy_score(y_test,predictions)
KNN_JaccardIndex = jaccard_score(y_test,predictions)
KNN_F1_Score = f1_score(y_test,predictions)

### Decision Tree


#### Q9) Create and train a Decision Tree model called Tree using the training data (`x_train`, `y_train`).


In [ ]:
#Enter Your Code, Execute and take the Screenshot

In [116]:
Tree = DecisionTreeClassifier(criterion="entropy",max_depth=5)
Tree.fit(x_train,y_train)

DecisionTreeClassifier(criterion='entropy', max_depth=5)

#### Q10) Now use the `predict` method on the testing data (`x_test`) and save it to the array `predictions`.


In [117]:
#Enter Your Code, Execute and take the Screenshot

In [118]:
predictions = Tree.predict(x_test)
predictions[0:5]

array([0., 0., 1., 0., 0.])

#### Q11) Using the `predictions` and the `y_test` dataframe calculate the value for each metric using the appropriate function.


In [119]:
#Enter Your Code, Execute and take the Screenshot

In [151]:
Tree_Accuracy_Score = metrics.accuracy_score(y_test,predictions)
Tree_JaccardIndex = jaccard_score(y_test,predictions)
Tree_F1_Score = f1_score(y_test,predictions)

### Logistic Regression


#### Q12) Use the `train_test_split` function to split the `features` and `Y` dataframes with a `test_size` of `0.2` and the `random_state` set to `1`.


In [85]:
#Enter Your Code, Execute and take the Screenshot

In [72]:
x_train, x_test, y_train, y_test = train_test_split(features,Y,test_size=0.2,random_state=1)
print("Train set:",x_train.shape,y_train.shape)
print("Test set:",x_test.shape,y_test.shape)

Train set: (2616, 66) (2616,)
Test set: (655, 66) (655,)


#### Q13) Create and train a LogisticRegression model called LR using the training data (`x_train`, `y_train`) with the `solver` parameter set to `liblinear`.


In [ ]:
#Enter Your Code, Execute and take the Screenshot

In [74]:
LR = LogisticRegression(C=0.01,solver="liblinear").fit(x_train,y_train)
LR

LogisticRegression(C=0.01, solver='liblinear')

#### Q14) Now, use the `predict` method on the testing data (`x_test`) and save it to the array `predictions`.


In [ ]:
#Enter Your Code, Execute and take the Screenshot

In [76]:
predictions = LR.predict(x_test)
predictions[0:5]

array([0., 0., 1., 0., 0.])

#### Q15) Using the `predictions` and the `y_test` dataframe calculate the value for each metric using the appropriate function.


In [ ]:
#Enter Your Code, Execute and take the Screenshot

In [150]:
LR_Accuracy_Score = metrics.accuracy_score(y_test,predictions)
LR_JaccardIndex = jaccard_score(y_test,predictions)
LR_F1_Score = f1_score(y_test,predictions)
LR_Log_Loss = log_loss(y_test,predictions)

### SVM


#### Q16) Create and train a SVM model called SVM using the training data (`x_train`, `y_train`).


In [ ]:
#Enter Your Code, Execute and take the Screenshot

In [135]:
SVM = svm.SVC(kernel='linear')
SVM.fit(x_train,y_train)

SVC(kernel='linear')

#### Q17) Now use the `predict` method on the testing data (`x_test`) and save it to the array `predictions`.


In [136]:
#Enter Your Code, Execute and take the Screenshot

In [137]:
predictions = SVM.predict(x_test)
predictions[0:5]

array([0., 0., 0., 0., 0.])

#### Q18) Using the `predictions` and the `y_test` dataframe calculate the value for each metric using the appropriate function.


In [149]:
SVM_Accuracy_Score = metrics.accuracy_score(y_test,predictions)
SVM_JaccardIndex = jaccard_score(y_test,predictions)
SVM_F1_Score = f1_score(y_test,predictions)

### Report


#### Q19) Show the Accuracy,Jaccard Index,F1-Score and LogLoss in a tabular format using data frame for all of the above models.

\*LogLoss is only for Logistic Regression Model


In [ ]:
#Enter Your Code, Execute and take the Screenshot

In [144]:
print("Report for KNN")
print('-'*50)
Report = {"Metrics":["Accuracy score","Jaccard score","F1 score"],"Result": [KNN_Accuracy_Score,KNN_JaccardIndex,KNN_F1_Score]}
pd.DataFrame(Report)

Report for KNN
--------------------------------------------------


Metrics    Result
0  Accuracy score  0.818321
1   Jaccard score  0.425121
2        F1 score  0.596610

In [145]:
print("Report for Decision Tree")
print('-'*50)
Report={"Metrics":["Accuracy score","Jaccard score","F1 Score"],"Result":[Tree_Accuracy_Score,Tree_JaccardIndex,Tree_F1_Score]}
pd.DataFrame(Report)

Report for Decision Tree
--------------------------------------------------


Metrics    Result
0  Accuracy score  0.806107
1   Jaccard score  0.433036
2        F1 Score  0.604361

In [153]:
print("Report for Logistic Regression")
print('-'*50)
Report={"Metrics":["Accuracy score","Jaccard index","F1 score","Log loss"],"Results":[LR_Accuracy_Score,LR_JaccardIndex,LR_F1_Score,LR_Log_Loss]}
pd.DataFrame(Report)

Report for Logistic Regression
--------------------------------------------------


Metrics   Results
0  Accuracy score  0.841221
1   Jaccard index  0.514019
2        F1 score  0.679012
3        Log loss  5.484059

In [148]:
print("Report for SVM")
print('-'*50)
Report={"Metrics":["Accuracy score","Jaccard score","F1 score"],"Results":[SVM_Accuracy_Score,SVM_JaccardIndex,SVM_F1_Score]}
pd.DataFrame(Report)

Report for SVM
--------------------------------------------------


Metrics   Results
0  Accuracy score  0.841221
1   Jaccard score  0.514019
2        F1 score  0.679012

<h2 id="Section_5">  How to submit </h2>

<p>Once you complete your notebook you will have to share it. You can download the notebook by navigating to "File" and clicking on "Download" button.

<p>This will save the (.ipynb) file on your computer. Once saved, you can upload this file in the "My Submission" tab, of the "Peer-graded Assignment" section.  


<h2>About the Authors:</h2> 

<a href="https://www.linkedin.com/in/joseph-s-50398b136/?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkML0101ENSkillsNetwork20718538-2022-01-01">Joseph Santarcangelo</a> has a PhD in Electrical Engineering, his research focused on using machine learning, signal processing, and computer vision to determine how videos impact human cognition. Joseph has been working for IBM since he completed his PhD.

### Other Contributors

<a href="https://www.linkedin.com/in/birlahimanshu/?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkML0101ENSkillsNetwork20718538-2022-01-01">Himanshu Birla</a>


## Change Log

| Date (YYYY-MM-DD) | Version | Changed By    | Change Description          |
| ----------------- | ------- | ------------- | --------------------------- |
| 2020-08-27        | 1.0     | Malika Singla | Added lab to GitLab         |
| 2022-06-22        | 2.0     | Lana K.       | Deleted GridSearch and Mock |
| <hr>              |         |               |                             |

## <h3 align="center"> © IBM Corporation 2020. All rights reserved. <h3/>
